-- AlterTable
ALTER TABLE "Department" ADD COLUMN     "CASE_STATUS_CLOSE" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "CASE_STATUS_COMPLETE" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "CASE_STATUS_OPEN" BOOLEAN NOT NULL DEFAULT false;
